[package.create.set]
# The image reference to use for the Pepr controller
pepr_image_domain = 'ghcr.io'
pepr_image = 'defenseunicorns/pepr/controller'
pepr_image_tag = 'v0.13.3'

# The image reference to use for the Zarf agent, defaults to a locally built image
agent_image_domain = 'ghcr.io/'
agent_image = 'defenseunicorns/zarf/agent'
agent_image_tag = 'v0.30.0'

registry_image_domain = ''
registry_image = ''
registry_image_tag = ''
