#log_level = 'debug'
architecture = 'amd64'

[package.create.set]
# The image reference to use for the Pepr controller
pepr_image_domain = 'ghcr.io'
pepr_image = 'defenseunicorns/pepr/controller'
pepr_image_tag = 'v0.14.1'

# The image reference to use for the Zarf agent, defaults to a locally built image
agent_image_domain = 'ghcr.io/'
agent_image = 'defenseunicorns/zarf/agent'
agent_image_tag = 'v0.30.0'

# The image reference to use for the ECR credential helper, defaults to a locally built image
credential_helper_image_domain = 'ghcr.io/'
credential_helper_image = 'defenseunicorns/zarf-init-aws/ecr-credential-helper'
credential_helper_image_tag = 'local'

registry_image_domain = ''
registry_image = ''
registry_image_tag = ''

[package.deploy]
components = 'zarf-ecr-credential-helper'

[package.deploy.set]
aws_region = 'us-east-1'
registry_type = ''
ecr_hook_role_arn = ''
ecr_credential_helper_role_arn = ''
