log_level: debug
architecture: amd64

package:
  create:
    set:
      # The image reference to use for the Pepr controller
      pepr_image_domain: ghcr.io
      pepr_image: defenseunicorns/pepr/controller
      pepr_image_tag: v0.19.0

      # The image reference to use for the Zarf agent
      agent_image_domain: ghcr.io/
      agent_image: defenseunicorns/zarf/agent
      agent_image_tag: v0.31.3

      # The image reference to use for the optional git-server Zarf deploys
      gitea_image: gitea/gitea
      gitea_server_version: 1.19.3

      registry_image_domain: ""
      registry_image: ""
      registry_image_tag: ""

  deploy:
    set:
      aws_region: us-east-1
      registry_type: ""
      ecr_role_arn: ""
