# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "###ZARF_VAR_EKS_CLUSTER_NAME###"
  region: "###ZARF_VAR_EKS_CLUSTER_REGION###"
  version: "###ZARF_VAR_EKS_CLUSTER_VERSION###"

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: "###ZARF_VAR_EBS_DRIVER_VERSION###"
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
- instanceType: "###ZARF_VAR_EKS_INSTANCE_TYPE###"
  name: "###ZARF_VAR_EKS_CLUSTER_NAME###-ng"
  minSize: 3
  maxSize: 6
  spot: true
  availabilityZones: ["us-east-1a", "us-east-1d", "us-east-1f"]
