name: Publish Zarf Init Package for AWS on Tag

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Install latest version of Zarf
        uses: defenseunicorns/setup-zarf@main

      - name: Install tools
        uses: defenseunicorns/zarf/.github/actions/install-tools@main

      - name: Build AWS init package for release
        run: make release-aws-init-package

      - name: Publish AWS Init Package as OCI and Skeleton
        run: make publish-aws-init-package ARCH=amd64 REPOSITORY_URL=ghcr.io/defenseunicorns/packages

      # Create a CVE report based on this build
      - name: Create release time CVE report
        run: make cve-report

      - name: Save CVE report
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: cve-report
          path: build/zarf-known-cves.csv

      # Create GitHub release and upload the AWS init package as a release artifact
      - name: Create GitHub release and upload AWS init package as release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: gh release create "$GITHUB_REF_NAME" ./build/zarf-init-*.tar.zst --generate-notes --verify-tag
