name: Validate Schema Generation
on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Install latest version of Zarf
        uses: defenseunicorns/setup-zarf@main

      - name: Check that 'make gen-schema' was ran
        run: make test-gen-schema

      - name: Save logs
        if: always()
        uses: defenseunicorns/zarf/.github/actions/save-logs@main
