name: Analyze CVEs

permissions:
  contents: read

on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - "**/package.json"
      - "**/package-lock.json"
      - "go.mod"
      - "go.sum"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

      - name: Install tools
        uses: defenseunicorns/zarf/.github/actions/install-tools@main

      - name: Install latest version of Zarf
        uses: defenseunicorns/setup-zarf@main

      - name: Check for CVEs in Dependencies
        run: make test-cves
