name: Validate Lint
on: pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup NodeJS
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install Node dependencies
        run: npm ci

      - name: Validate formatting of all typescript code in the repository
        run: make lint-ts

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
