name: Validate Labels
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

permissions:
  contents: read

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024 # 2.2.2
        with:
          BANNED_LABELS: "needs-docs,needs-tests,needs-adr,needs-git-sign-off,needs-tutorial"
