name: Validate Schema Generation
on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

      - name: Setup Go
        uses: defenseunicorns/zarf/.github/actions/golang@main

      - name: Check that 'make gen-schema' was ran
        run: make test-gen-schema

      - name: Save logs
        if: always()
        uses: defenseunicorns/zarf/.github/actions/save-logs@main
